#!/bin/bash

# 下载什么
SEHLL_NAME=$1
# 哪个版本
SEHLL_VERSION=$2

function on_fail() {
	SEHLL_NAME=""
	SEHLL_VERSION=""
	printf "\n> \033[31m下载失败！\033[0m\n\n"
}

function start() {
	case $SEHLL_VERSION in
		'') SEHLL_VERSION='master';;
		*) ;;
	esac
	curl -s https://cdn.jsdelivr.net/gh/xaoxuu/${SEHLL_NAME}@${SEHLL_VERSION}/install | sh || on_fail
}

function check_param() {
		case $SEHLL_NAME in
			'')
				echo "======================= Shell Scripts ======================="
				printf "可安装的脚本:\n"
				printf "  \033[1m\033[32m%s\033[0m %s \t %s \n" 'hexo.sh' '' 'https://xaoxuu.com/wiki/hexo.sh/'
				printf "  \033[1m\033[32m%s\033[0m %s \t %s \n" 'podspec.sh' '' 'https://xaoxuu.com/wiki/podspec.sh/'
				printf "  \033[1m\033[32m%s\033[0m %s \t %s \n" 'vim-cn.sh' '' 'https://xaoxuu.com/wiki/vim-cn.sh/'
				printf "\n"
				printf "提示:\n"
				printf "  可以在脚本后面加上版本号，用空格隔开。\n"
				printf "  不加版本号默认安装最新版。\n"
				printf "\n"
				printf "例如:\n"
				printf "> curl -s https://xaoxuu.com/install | sh -s vim-cn.sh v2\n"
				echo '-------------------------------------------------------------'
			;;
			*) start ;;
		esac
}

check_param
